### ISSUE TITLE
Navbar(mobile) does not close on click

### ISSUE THREAD

**Issue by baxelson12** [mdbootstrap/Angular-Bootstrap-with-Material-Design#28]
I just updated to the latest version of mdbootstrap and expected this to be fixed.  Viewing on mobile, clicking a link within a navbar or clicking outside of navbar does not close said navbar.  Is it just me or is this still a standing issue?

**Repro:**
1.)
```
<!--Navbar-->
<mdb-navbar SideClass="navbar navbar-expand-lg navbar-dark indigo">
           
    <!-- Navbar brand -->
    <logo><a class="navbar-brand" href="#">Navbar</a></logo>

    <!-- Collapsible content -->
    <links>

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link waves-light" mdbRippleRadius>Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-light" mdbRippleRadius>Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link waves-light" mdbRippleRadius>Pricing</a>
            </li>

            <!-- Dropdown -->
            <li class="nav-item dropdown" dropdown>
                <a dropdownToggle mdbRippleRadius type="button" class="nav-link dropdown-toggle waves-light" mdbRippleRadius>
                Basic dropdown<span class="caret"></span></a>
                <div *dropdownMenu class="dropdown-menu dropdown dropdown-primary" role="menu">
                    <a class="dropdown-item waves-light" mdbRippleRadius href="#">Action</a>
                    <a class="dropdown-item waves-light" mdbRippleRadius href="#">Another action</a>
                    <a class="dropdown-item waves-light" mdbRippleRadius href="#">Something else here</a>
                    <div class="divider dropdown-divider"></div>
                    <a class="dropdown-item waves-light" mdbRippleRadius href="#">Separated link</a>
                </div>
            </li>

        </ul>
        <!-- Links -->

        <!-- Search form -->
        <form class="form-inline  waves-light" mdbRippleRadius>
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
        </form>
    </links>
    <!-- Collapsible content -->

</mdb-navbar>
<!--/.Navbar-->
```
2.) View on mobile.

**P.S** - This does not work on your Angular docs either.

Thanks,
Brad

**Comment by sandangel** [comment]
We are working on a fix. Thanks for reporting.

**Comment by baxelson12** [comment]
My solution for this was two part.  To watch if the user clicks off of the menu, I watched for click events like so
```
@Component({
  selector: 's-navbar',
  host: {
  //Get document click events
  '(document:click)': 'onClick($event)',
  },
  template: ...
})
```

I had to add in a variable `this.nav.burger` to /src/navbars/navbar.component.ts that monitors true/false if the menu is presented collapsed or full and then get a reference to that navbar. 
```
@ViewChild('navbar') nav;
  //When there is a click on document....
  onClick(event) {
    //If it's not within the navbar, and this is a collapsible menu...
    if (!this.nav.navbar.nativeElement.contains(event.target) && this.nav.burger) {
      this.nav.hide();
    }
  }
```

Then lastly, I created a directive for links.
```
import { Directive,
         ViewChild,
         ElementRef,
         Input
       } from '@angular/core';

@Directive({
  selector: '[navItem]',
  host: {
    '(click)': 'onClick()'
  }
})
export class MdMenuItemDirective {
  @Input() parent;

  onClick():void {
    if (this.parent.burger) {
        this.parent.hide();
    }  
  }

  constructor(el: ElementRef) {
    let nativeEl = el.nativeElement;
    if (nativeEl.tagName === "A") {
      nativeEl.className += 'nav-link';  
    }
  }

}
```

Actual navbar markup.
```
<!--Navbar-->
<!-- Note the #navbar -->
<mdb-navbar #navbar SideClass="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar blue-grey" [class.default-color]="navIsClear">
    <logo><a class="navbar-brand" href="#">Your company here</a></logo>
    <links>
        <!-- Links -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item" routerLinkActive="active">
              <!-- input [parent] to get reference to navbar component -->
                <a navItem [parent]="navbar" routerLink="/home">Home</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a navItem [parent]="navbar" routerLink="/about">About</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a navItem [parent]="navbar" routerLink="/contact">Contact</a>
            </li>
            <li class="nav-item" routerLinkActive="active">
                <a navItem [parent]="navbar" routerLink="/shop">Shop</a>
            </li>
        </ul>
    </links>
</mdb-navbar>
<!--/.Navbar-->
```

There's probably a much better way to do this, but this seems to work for me for the time being.

**Comment by Bloodcast69** [comment]
Hello guys,
We have uploaded fix for this case to our dev branch. You can download it without problems.
In next few days we'll put bunch of fixes to our master branch. This update will include fix for nav too.

Best Regards,
Damian

**Comment by Tooluloope** [comment]
Thanks for the fix @Bloodcast69, but After clicking a Dropdown item the nav bar still doesn't collapse

**Comment by mdbootstrap** [comment]
@Tooluloope could you please temporarily remove mdbRippleRadius directive from dropdown component to check if that helps?

**Comment by dec23rd1986** [comment]
Any update on this? My navbar still won't collapse once clicked on an item.

**Comment by Bloodcast69** [comment]
dec23rd1986 - which problem did you encounter? Navbar doesn't close after clicking in mobile view? If yes, please add routerLink="/" to every <a> element.

Please give me more information.
Best Regards,
Damian

**Comment by dec23rd1986** [comment]
Hi there, I added the routerLink code and it's still not working. I pasted my code here for reference. 


           
           <div class="collapse navbar-collapse text-center" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">

                  <li class="nav-item" routerLink="/about">
                    <a class="nav-link"
                    href="#about_link"  style="color:#FFF;">About</a>
                </li>

                <li class="nav-item" routerLink="/schedule">
                    <a class="nav-link"
                    href="#schedule_link" style="color:#FFF;">Schedule</a>
                </li>

                
                <li class="nav-item" routerLink="/instagram">
                    <a class="nav-link" href="https://www.instagram.com/ridewithamy/" title="Follow on Instagram" target="_blank"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#FFF;"></i></a></li>

                    <li class="nav-item" routerLink="/facebook">
                        <a class="nav-link" href="https://www.facebook.com/amy.kaczmarek.3" title="Follow on Linkedin" target="_blank"><i class="fa fa-facebook fa-lg" aria-hidden="true" style="color:#FFF;"></i></a></li>
                    </ul>
                </div>
            </nav>

**Comment by Bloodcast69** [comment]
Dear @dec23rd1986 please add routerLink to <a>'s elements instead of <li>'s. That should work now. If not, please check if you have configured routes correctly.
Best Regards,
Damian

**Comment by dec23rd1986** [comment]
I switched routerlink to the <a> tag rather than <li> still isn't working. Not sure what is wrong as there is not much research to find solution. 

        <nav class="navbar navbar-expand-sm navbar-dark fixed-top scrolling-navbar" style="background-color:#7e57c2;">

           <a class="navbar-brand" href="index.html" style="color:#FFF;"><i class="fa fa-gratipay fa-lg"></i><b> Ride with Amy</b></a>

            
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
           aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon" style="color:#FFF;"></span></button>


           
           <div class="collapse navbar-collapse text-center" id="navbarResponsive">
              <ul class="navbar-nav ml-auto">

                  <li class="nav-item" >
                    <a class="nav-link"
                    href="#about_link"  style="color:#FFF;" routerLink="/about">About</a>
                </li>

                <li class="nav-item" >
                    <a class="nav-link"
                    href="#schedule_link" style="color:#FFF;" routerLink="/schedule">Schedule</a>
                </li>

                
                <li class="nav-item" >
                    <a class="nav-link" href="https://www.instagram.com/ridewithamy/" title="Follow on Instagram" target="_blank" routerLink="/instagram"><i class="fa fa-instagram fa-lg" aria-hidden="true" style="color:#FFF;"></i></a></li>

                    <li class="nav-item" >
                        <a class="nav-link" href="https://www.facebook.com/amy.kaczmarek.3" title="Follow on Linkedin" target="_blank" routerLink="/facebook"><i class="fa fa-facebook fa-lg" aria-hidden="true" style="color:#FFF;"></i></a></li>
                    </ul>
                </div>
            </nav>

**Comment by Bloodcast69** [comment]
Wait a moment... Are you using code from jQuery instead of Angular one? It's looks like jQuery.
Please use navbar code for Angular: https://mdbootstrap.com/angular/components/navbars/ , and add routerLink="/" to every a element.
Best Regards,
Damian

**Comment by WillTartak** [comment]
What worked for me was to add the dropdownToggle directive to each of the link <a> tags. One of mine looks like this:

`<a class='dropdown-item waves-effect waves-light' mdbRippleRadius (click)="logout()" href="#" dropdownToggle>Logout</a>`

**Comment by dec23rd1986** [comment]
I still can't make it work. What is strange is how when I click the toggle button, it opens up out of the page rather than down.

**Comment by Bloodcast69** [comment]
Dear @dec23rd1986 we're providing dropup variation of dropdown. Instead of dropping down elements, it's dropping up. Maybe you're using this type of dropdown?

**Comment by dec23rd1986** [comment]
Hi @Bloodcast69, 

I think I'm missing a few things here: 

1. What can I do to make the toggler open down rather than up? I don't like the toggler opening up as it opens up off the page and I can't see my beginning elements. 
2. Lastly, with the toggle not closing on click, is there a plugin that I'm missing? Or, will it work when including routerLink="/" to every a element in the HTML file alone. I have never worked with angular so I'm not sure if there is an angular piece I'm missing as I'm only working with my HTML file right now? 

I hope this makes sense. Thanks!

**Comment by Bloodcast69** [comment]
Dear @dec23rd1986 
1st question: There you can find every information that you need to use our dropdowns: https://mdbootstrap.com/angular/components/dropdowns/#introduction

2nd question: If you're thinking about closing navbar hamburger after clicking on some items when mobile, you have to add routerLink with some specific address (for example, for your home link, routerLink="/home". 

But if you're not thinking about navbar, but dropdowns, there's already implemented a solution, to close one dropdown after clicking on another one.

Hope that my answer is clear to you. If not, feel free to ask me more.
Best Regards,
Damian

**Comment by daveparks23** [comment]
None of the solutions listed here work for me.  Is there a tutorial from scratch out there?  There are soooo many things that could have gone wrong here.

`<mdb-navbar SideClass="navbar navbar-expand-lg navbar-dark bg-elegant scrolling-navbar fixed-top" >
  <logo>
      <a class="logo navbar-brand deep-orange-text" href="#"><strong>Howard Measurement</strong></a>
  </logo>
  <links>
      <ul class="navbar-nav mr-auto" *ngIf="isLoggedIn" >
          <li class="nav-item waves-light" mdbRippleRadius>
              <a class="nav-link" [routerLink]="['/users']" *ngIf="userAdmin" >Users<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item waves-light" mdbRippleRadius>
              <a class="nav-link" [routerLink]="['/customers']"  >Customers</a>
          </li>
          <li class="nav-item waves-light" mdbRippleRadius>
              <a class="nav-link" routerLink]="['/stations']" >Stations</a>  
          </li>
          <li class="nav-item waves-light" mdbRippleRadius>
              <a class="nav-link" routerLink]="['/']">Tags</a>
          </li>
      </ul>`

**Comment by dec23rd1986** [comment]
@daveparks23 
I never found a solution via mdbootstrap, however through much digging I found out that this is a common issue. Someone via stack overflow came up with a solution that has worked wonders for me. You can read about it here: [https://stackoverflow.com/questions/42401606/how-to-hide-collapsible-bootstrap-4-navbar-on-click/42401686#42401686](url)

I included this code in my jQuery section at the end of my index page: 
<script>
            $('.navbar-nav>li>a').on('click', function(){
              $('.navbar-collapse').collapse('hide');
            });</script>
Hope that works for you!
-Andrea

**Comment by rgaliardi** [comment]
New!
html:
<div class='main-nav'>
    <div class='navbar navbar-inverse'>
        <div class='navbar-header'>
            <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
                <span class='sr-only'>Toggle navigation</span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
                <span class='icon-bar'></span>
            </button>
            <a class='navbar-brand' [routerLink]="['/home']">PoC_ASPNET_Core_Angular</a>
        </div>
        <div class='clearfix'></div>
        <div class='navbar-collapse collapse'>
            <ul class='nav navbar-nav'>
                <li [routerLinkActive]="['link-active']" (click)="onMenuClick()">
                    <a [routerLink]="['/home']">
                        <span class='glyphicon glyphicon-home'></span> Home
                    </a>
                </li>
                <li [routerLinkActive]="['link-active']" (click)="onMenuClick()">
                    <a [routerLink]="['/counter']">
                        <span class='glyphicon glyphicon-education'></span> Counter
                    </a>
                </li>
                <li [routerLinkActive]="['link-active']" (click)="onMenuClick()">
                    <a [routerLink]="['/fetch-data']">
                        <span class='glyphicon glyphicon-th-list'></span> Fetch data
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

ts:
import { Component, ElementRef, Renderer } from '@angular/core';
import { Directive } from '@angular/core/src/metadata/directives';

@Component({
    selector: 'nav-menu',
    templateUrl: './navmenu.component.html',
    styleUrls: ['./navmenu.component.css'],
})

export class NavMenuComponent {
    constructor(private el: ElementRef, private renderer: Renderer) { }

    onMenuClick() {
        this.renderer.setElementClass(this.el.nativeElement.querySelector('.navbar-collapse'), 'in', false);
    }
}

**Comment by stathoula** [comment]
This worked for me: <br><br>
app.component.html

    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="col-md-12">
          <div class="navbar-header page-scroll">
          <button id ="navButton" style="color:red"type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" routerLink="/"><img id="navbrand" class="site-logo"  src="assets/img/yayaka_logo.png"/></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="hidden">
              <a href="#page-top"></a>
            </li>
            <li class="dropdown" appDropdown>
              <a class="dropdown-toggle" style="cursor: pointer;">
                ΤΙ ΕΙΝΑΙ ΤΟ yayaka<span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a (click) = "closeMenu()" href="/#about">About</a></li>
                <li><a (click) = "closeMenu()" href="/#services">Services</a></li>
              </ul>
            </li>
            <li class="page-scroll">
              <a (click) = "closeMenu()" routerLink="/profiles"><strong>Profiles</strong></a>
            </li>
          </ul>
        </div>
      </div>
      </div>
    </nav>


app.component.ts
<br>

     closeMenu() {
        var isMobile = /iPhone|iPad|iPod|BlackBerry|Opera Mini|IEMobile|Android/i.test(navigator.userAgent);
        if (isMobile) {
          document.getElementById('navButton').click();
        }
      }

Hope it helps :)

**Comment by Umer-Aziz** [comment]
<bootstrap navbar not collapse but if we add js :
# $(document).ready(function () {
        $(".navbar-nav li a").click(function (event) {
          $(".navbar-collapse").collapse("hide");
        });
<it works but if you have dropdown menu u need to add new class in list item li on every list <item but dropdown menu remain.here is js 

# $(document).ready(function () {
        $(".navbar-nav .new a").click(function (event) {
          $(".navbar-collapse").collapse("hide");
        });

 
< 
<here is my navbar index.html

# <section id="nav-bar">
      <nav class="navbar navbar-expand-lg navbar-dark fixed-top">
        <a class="navbar-brand" href="#"
          ><img src="images/logo.png" alt="logo"
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item new">
              <a class="nav-link" href="#nav-bar">HOME</a>
            </li>
            <li class="nav-item new">
              <a class="nav-link" href="#SERVICES">SERVICES</a>
            </li>

            <li class="nav-item dropdown">
              <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdown"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >
                PROJECTS
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#PROJECT">All Project</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/project1.html">Project-1</a>
                <a class="dropdown-item" href="/project2.html">Project-2</a>
                <a class="dropdown-item" href="/project3.html">Project-3</a>
              </div>
            </li>

            <li class="nav-item new">
              <a class="nav-link" href="#TESTIMONIALS">TESTIMONIALS</a>
            </li>
            <li class="nav-item new">
              <a class="nav-link" href="#about-us">ABOUT US</a>
            </li>
            <li class="nav-item new">
              <a class="nav-link" href="#CONTACT">CONTACT</a>
            </li>
          </ul>
        </div>
      </nav>
    </section>

**Comment by YavorGrancharov** [comment]
This was the fix for me
```
<div class="row root-container">
  <nav class="navbar navbar-expand-xl navbar-dark bg-dark">
    <a class="navbar-brand navbar-left pull-left" [routerLink]="['/']">
      <img class="logo" src="../../assets/images/ailgo_logo.png" />
    </a>
    <button
      type="button"
      aria-label="Toggle navigation"
      class="navbar-toggler pull-right"
      data-toggle="collapse"
      data-target="#navbarNav"
      aria-expanded="false"
      #navbarNav
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse bg-dark" id="navbarNav">
      <ul class="nav navbar-nav mr-auto" (click)="onResize()">
        <li class="nav-item-active">
          <a class="nav-link" [routerLink]="['/']"
            ><button data type="button" class="btn btn-dark">
              {{ "NAVIGATION.HOME" | translate }}
            </button></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/history']">
            <button type="button" class="btn btn-dark">
              {{ "NAVIGATION.HISTORY" | translate }}
            </button></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/realtime']">
            <button type="button" class="btn btn-dark">
              {{ "NAVIGATION.REAL_TIME" | translate }}
            </button></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" [routerLink]="['/contact']">
            <button type="button" class="btn btn-dark">
              {{ "NAVIGATION.CONTACT_US" | translate }}
            </button></a
          >
        </li>
        <li class="nav-item" *ngIf="authService.currentUserValue">
          <a class="nav-link" (click)="authService.logout()">
            <button type="button" class="btn btn-dark">
              {{ "LOGOUT" | translate }}
            </button></a
          >
        </li>
        <li class="nav-item" *ngIf="!authService.currentUserValue">
          <a class="nav-link" [routerLink]="['/login']">
            <button type="button" class="btn btn-dark">
              {{ "NAVIGATION.LOGIN" | translate }}
            </button></a
          >
        </li>
      </ul>
      <span
        class="name form-inline btn btn-dark mr-2"
        *ngIf="authService.currentUser$ | async as user"
      >
        {{ "USER.GREETING" | translate: { name: user.name | json } }}</span
      >
      <form class="form-inline my-2 my-lg-0">
        <span class="form-inline">
          <select
            class="lang-selector form-control mr-2"
            #selectedLang
            (change)="switchLang(selectedLang.value)"
          >
            <option
              *ngFor="let language of translateService.getLangs()"
              [value]="language"
              [selected]="language === translateService.currentLang"
            >
              {{ "LANGUAGES." + language | translate }}
            </option>
          </select>
        </span>
        <div class="input-group">
          <input
            placeholder="{{ 'NAVIGATION.SEARCH' | translate }}"
            aria-label="Recipient's username"
            aria-describedby="basic-addon2"
            class="form-control"
          />
          <div class="input-group-append">
            <button type="button" class="btn btn-light">
              <i class="fa fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </form>
    </div>
  </nav>
</div>
```


```
import {
  Component,
  ElementRef,
  HostListener,
  ViewChild,
} from '@angular/core';

import { TranslateService } from '@ngx-translate/core';
import { AuthService } from '../../services/auth.service';

import { Languages } from 'src/libs/models/lib/language.model';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss'],
})
export class NavbarComponent {
  @ViewChild('navbarNav', { static: false }) navbarNav: ElementRef;
  name: string;
  isCollapsed = false;
  breakingPoint = 1200;

  constructor(
    public translateService: TranslateService,
    public authService: AuthService
  ) {}

  switchLang(lang: Languages): void {
    this.translateService.use(lang);
  }

  @HostListener('window:resize', [])
  onResize() {
    this._closeMenu(window.innerWidth);
  }

  private _closeMenu(width: number) {
    if (width < this.breakingPoint) {
      this.navbarNav.nativeElement.click();
    }
  }
}
```
